name: Active and Co
description: Web and mobile application design and development.
markdown: kramdown
highlighter: 'pygments'
timezone: Europe/Paris
relative_permalinks: false
url: https://activeand.co
exclude:
  - bin
  - css/main.styl
  - Dockerfile.codex
  - node_modules
  - package-lock.json
  - package.json
  - TODO.md

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: "pages/fr"
    values:
      lang: fr
