name: Active and Co
markdown: kramdown
highlighter: 'pygments'
timezone: Europe/Paris
relative_permalinks: false
url: http://activeand.co
exclude: [node_modules]

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
